export class Downloadmandategrid {

    //IsExcelMandateDownload: boolean;
    //IsSnapMandateDownload: boolean;
    //IsMobileData: boolean;
    //createdon: string;
    //JPGPath: string;
    //IsScan: string;
    //TIPPath: string;
    //IsPrint: string;
    //mandateid: string;
    //BankName: string;
    //status: string;
    //Amount: string;
    //Code: string;
    //BankName1: string;
    //DateOnMandate: string;
    //AcNo: string;
    //Refrence1: string;
    //FromDate: string;
    //Customer1: string;
    //DebitType: string;
    //Frequency: string;
    //ToDebit: string;

    mandateid: string;
    Customer1: string;
    DateOnMandate: string;
    IsPrint: string;
    IsScan: string;
    Refrence1: string;
    Amount: string;
    AcNo: string;
    Code: string;
    BankName: string;
    Frequency: string;
    DebitType: string;
    ToDebit: string;
    createdon: string;

//    Message ID: string;
//    Message Creation Date Time: string;
//    Initiating Party ID: string;
//    Instructing Member ID: string;
//    Instructed Agent Member ID: string;
//    Instructed Agent Name: string;
//    Mandate Request ID: string;
//    Mandate Category: string;
//    Mandate Category Name: string;
//    TXN type: string;
//    Recurring or One-Off(RCUR, OOFF): string;
//Frequency: string;
//First Collection Date: string;
//    Final Collection Date: string;
//Collection Amount: string;
//Maximum Amount: string;
//Utility Code: string;
//Sponsor Bank Code: string;
//Debtor Name / Name of Account Holder: string;
//Consumer Reference No: string;
//Scheme / Plan Reference No: string;
//Debtor Mobile No: string;
//Debtor Email - Id: string;
//Debtor other details: string;
//Destination Bank Account Number / Legal Account Number: string;
//Destination Bank Account Type: string;
//Destination Bank IFSC / MICR code: string;
//Destination Bank Name: string;

}
